language: rust
rust: stable
cache: cargo
before_install:
  - sudo add-apt-repository -y ppa:duggan/bats
  - sudo apt-get update
  - sudo apt-get -y install bats
before_script: (cargo install rustfmt || true)
sudo: false
git:
  depth: 1
script:
  - ci/run-travis.sh
