[package]
name = "task1"
version = "0.1.0"
authors = ["Joshua Rutschmann <joshua.rutschmann@gmx.de>"]

[dependencies]
sha2 = "0.7.0"
clap = {version = "~2.29.0", features = ["yaml"]}
time = "0.1"
sys-info = "*"
