[package]
name = "task2"
version = "0.1.0"
authors = ["Joshua Rutschmann <joshua.rutschmann@gmx.de>"]

[dependencies]
srv-commands = { path = "srv-commands" }
srv-config = { path = "srv-config" }

[workspace]
