[package]
name = "task1"
version = "0.2.0"
authors = ["Joshua Rutschmann <joshua.rutschmann@gmx.de>", "Lorenz Bung <lorenz.bung@htwg-konstanz.de>"]

[dependencies]
srv-config = { path = "srv-config" }
srv-hasher = { path = "srv-hasher" }

[workspace]
